### ISSUE TITLE
Acquisto ps5

### ISSUE THREAD

**Issue by ragnar-homekit** [simonecarlax/ps5-bot-amazonitalia#1]
Ciao tu sei riuscito ad acquistarla con questo bot?

una volta avviato poi eventualmente terminerà l’acquisto direttamente con il metodo di pagamento e l’indirizzo di spedizione impostati come predefiniti?

**Comment by simonecarlax** [comment]
Ciao, non sono interessato all'acquisto della PS5 pertanto non faccio girare lo script personalmente, ma ho feedback continui da chi lo sta facendo.
Lo script simula il comportamento umano di: Aggiorno la pagina -> C'è il tasto "Acquista ora"? (ciò ne implica la disponibilità) -> Premilo e fermati, altrimenti ricomincia.
Quindi si, l'acquisto terminerà con pagamento e domicilio predefiniti.
